apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sro-operator-subscription
  namespace: openshift-special-resource-operator
spec:
  channel: stable
  name: special-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
