apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: "mcp"
status:
  configuration:
    source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 95-talm-initiated-reboot-$mcp
  conditions:
  - type: Updated
    status: "True"
  - type: Updating
    status: "True"
