apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator-namespace.yaml
  - operator-operatorgroup.yaml
  - operator-catalogsource.yaml
  - operator-subscription.yaml

