apiVersion: ptp.openshift.io/v1
kind: PtpOperatorConfig
metadata:
  name: default
  namespace: openshift-ptp
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.daemonNodeSelector }}
  daemonNodeSelector:
    {{ template "matchNodeSelector" (list .spec.daemonNodeSelector "node-role.kubernetes.io" ) }}
  {{- end }}
  ptpEventConfig:
    {{- if .spec.ptpEventConfig.apiVersion }}
    apiVersion: {{ .spec.ptpEventConfig.apiVersion }}
    {{- end }}
    enableEventPublisher: true
    transportHost: {{ .spec.ptpEventConfig.transportHost }} # "http://ptp-event-publisher-service-NODE_NAME.openshift-ptp.svc.cluster.local:9043"
