apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
  namespace: openshift-sriov-network-operator
spec:
  enableInjector: true
  enableOperatorWebhook: true
  configDaemonNodeSelector:
    "node-role.kubernetes.io/$mcp": ""
  disableDrain: false
