apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
  namespace: openshift-sriov-network-operator
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.configDaemonNodeSelector }}
  configDaemonNodeSelector:
    {{ template "matchNodeSelector" (list .spec.configDaemonNodeSelector "node-role.kubernetes.io" ) }}
  {{- end }}
  # Injector and OperatorWebhook pods can be disabled (set to "false") below
  # to reduce the number of management pods. It is recommended to start with the 
  # webhook and injector pods enabled, and only disable them after verifying the
  # correctness of user manifests.
  #   If the injector is disabled, containers using sr-iov resources must explicitly assign
  #   them in the  "requests"/"limits" section of the container spec, for example:
  #    containers:
  #    - name: my-sriov-workload-container
  #      resources:
  #        limits:
  #          openshift.io/<resource_name>:  "1"
  #        requests:
  #          openshift.io/<resource_name>:  "1"
  {{- if hasKey .spec "enableInjector" }}
  enableInjector: false
  {{- end }}
  {{- if hasKey .spec "enableOperatorWebhook" }}
  enableOperatorWebhook: false
  {{- end }}
  {{- if hasKey .spec "logLevel" }}
  logLevel: 0
  {{- end }}
