generators:
# This is common to all RAN deployments
- common-ranGen.yaml
# This group policy is for all single-node deployments:
- group-du-sno-ranGen.yaml
# This group validator policy is for all single-node deployments:
- group-du-sno-validator-ranGen.yaml
# This group policy is for all compressed 3-node cluster deployments:
- group-du-3node-ranGen.yaml
# This group validator policy is for all compressed 3-node cluster deployments:
- group-du-3node-validator-ranGen.yaml
# This group policy is for all standard cluster deployments:
- group-du-standard-ranGen.yaml
# This group validator policy is for all standard cluster deployments:
- group-du-standard-validator-ranGen.yaml
# These are examples that should be replicated for every individual site:
- example-sno-site.yaml
- example-multinode-site.yaml

resources:
- ns.yaml


# Updates to the PerformanceProfile or MachineConfigurations may take a short period of time before 
# causing the MachineConfigPool to move to degraded. This patch adds an annotation to validator policy.
# This soak time ensures that the upgrading status can be set prior to considering the validation policy
# in compliance
patches:
- patch: |-
    apiVersion: policy.open-cluster-management.io/v1
    kind: Policy
    metadata:
      annotations:
        ran.openshift.io/soak-seconds: "30"

      # The 'name' and 'namespace' values must match the values in the validator policy
      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
      name: group-du-sno-validator-4.14-du-policy
      namespace: ztp-group
- patch: |-
    apiVersion: policy.open-cluster-management.io/v1
    kind: Policy
    metadata:
      annotations:
        ran.openshift.io/soak-seconds: "30"

      # The 'name' and 'namespace' values must match the values in the validator policy
      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
      name: group-du-3node-validator-4.14-du-policy
      namespace: ztp-group
- patch: |-
    apiVersion: policy.open-cluster-management.io/v1
    kind: Policy
    metadata:
      annotations:
        ran.openshift.io/soak-seconds: "30"

      # The 'name' and 'namespace' values must match the values in the validator policy
      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
      name: group-du-standard-validator-4.14-du-policy
      namespace: ztp-group

