generators:
# This is common to all RAN deployments
- common-ranGen.yaml
# This group policy is for all single-node deployments. Use just one of the 2 below.
- group-du-sno-ranGen.yaml
#- hub-side-templating/group-du-sno-ranGen-templated.yaml
# This group validator policy is for all single-node deployments.
- group-du-sno-validator-ranGen.yaml
# This group policy is for all compressed 3-node cluster deployments. Use just one of the 2 below.
- group-du-3node-ranGen.yaml
#- hub-side-templating/group-du-3node-ranGen-templated.yaml
# This group validator policy is for all compressed 3-node cluster deployments:
- group-du-3node-validator-ranGen.yaml
# This group policy is for all standard cluster deployments. Use just one of the 2 below.
- group-du-standard-ranGen.yaml
#- hub-side-templating/group-du-standard-ranGen-templated.yaml
# This group validator policy is for all standard cluster deployments:
- group-du-standard-validator-ranGen.yaml
# These are examples that should be replicated for every individual site. Use just one for each cluster configuration.
- example-sno-site.yaml
- example-multinode-site.yaml

resources:
- ns.yaml
# The resources from below are only needed if policies from hub-side-templating are used.
- hub-side-templating/configMaps/group-hardware-types-configmap.yaml
- hub-side-templating/configMaps/group-zones-configmap.yaml
- hub-side-templating/configMaps/site-data-configmap.yaml
# This policy removes Cluster Logging operator 5.x artifacts after upgrading to 6.x
- group-du-clo5-cleanup-policy.yaml

# Updates to the PerformanceProfile or MachineConfigurations may take a short period of time before 
# causing the MachineConfigPool to move to degraded. This patch adds an annotation to validator policy.
# This soak time ensures that the upgrading status can be set prior to considering the validation policy
# in compliance
#patches:
#- patch: |-
#    apiVersion: policy.open-cluster-management.io/v1
#    kind: Policy
#    metadata:
#      annotations:
#        ran.openshift.io/soak-seconds: "30"
#
#      # The 'name' and 'namespace' values must match the values in the validator policy
#      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
#      name: group-du-sno-validator-latest-du-policy
#      namespace: ztp-group
#- patch: |-
#    apiVersion: policy.open-cluster-management.io/v1
#    kind: Policy
#    metadata:
#      annotations:
#        ran.openshift.io/soak-seconds: "30"
#
#      # The 'name' and 'namespace' values must match the values in the validator policy
#      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
#      name: group-du-3node-validator-latest-du-policy
#      namespace: ztp-group
#- patch: |-
#    apiVersion: policy.open-cluster-management.io/v1
#    kind: Policy
#    metadata:
#      annotations:
#        ran.openshift.io/soak-seconds: "30"
#
#      # The 'name' and 'namespace' values must match the values in the validator policy
#      # the policy name format is as {name}-{spec.sourceFiles[x].policyName}
#      name: group-du-standard-validator-latest-du-policy
#      namespace: ztp-group
