---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-dpdk-app
  namespace: dpdk
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: s2i-dpdk
    app.kubernetes.io/component: s2i-dpdk
    app.kubernetes.io/instance: s2i-dpdk
  name: s2i-dpdk
  namespace: dpdk
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: s2i-dpdk-app:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: tools/s2i-dpdk/test/test-app
    git:
      uri: https://github.com/openshift-kni/cnf-features-deploy.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: quay.io/schseba/dpdk-s2i-base:ds
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
