apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO handle namespace with var

resources:
  - operator-namespace.yaml
  - operator_operatorgroup.yaml
  - operator_catalogsource.yaml
  - operator_subscription.yaml
