apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator
  namespace: openshift-performance-addon
spec:
  channel: "4.5"
  name: performance-addon-operator
  source: performance-addon-operator
  sourceNamespace: openshift-marketplace
