name: "Validate renovate.json config file"

on:
  pull_request:
    branches: 
      - master
    paths:
      - renovate.json
  workflow_dispatch:
   
jobs:
  renovate-config-file-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: konflux-ci/renovate-config-validator-action@main
        with:
          config_file: renovate.json